### ISSUE TITLE
Resource grafana_data_source does not configure password

### ISSUE THREAD

**Issue by narsats** [grafana/terraform-provider-grafana#112]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/aws v3.1.0
+ provider registry.terraform.io/terraform-providers/grafana v1.5.0
+ provider registry.terraform.io/terraform-providers/influxdb v1.3.0

### Affected Resource(s)
- grafana_data_source

### Terraform Configuration Files
```hcl
resource "grafana_data_source" "influx_metrics" {
  type          = "influxdb"
  name          = "Test"
  url           = "https://influx.myurl.com"
  username      = "terraform-test"
  password      = "terraform-test"
  database_name = "terraform-test"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Datasource should have been created with the password configured

### Actual Behavior
Datasource was created, password not configured and therefore not usable until password manually supplied.
![influx_details](https://user-images.githubusercontent.com/56370038/90245087-98e49800-ddf7-11ea-8e85-c5382772bf78.jpg)

### Steps to Reproduce
Configure a grafana_data_source, and apply the configuration

### Important Factoids
This was tested with these versions in Windows/Linux without success:
Terraform 0.13, 0.12, 0.10
Grafana 1.5.0, 1.4.0, 1.3.0, 1.1.0

### References
Couldn't find any other related information

**Comment by jychen7** [comment]
from Grafana 1.7.0, I also see UI shows empty password. But calling Grafana API '/api/datasources/:id', I can see password is actually set. And Grafana connect to the database successfully, so it indeed has password. (I verify unauthorise if no password).

So I am afraid it is Grafana UI bug, not this provider bug

**Comment by inkel** [comment]
This indeed should belong to the Grafana UI project, however, I don't think it's a bug but rather a security feature, as passwords are not stored in plain text format but in a hashed form, thus it's impossible to populate the UI form with the value you entered.

I just tried creating a datasource with a password and I was able to successfully connect to the database.

Last but not least, note that you're using a really outdated Terraform version. It has been in 1.x since June 2021.

**Comment by dryewo** [comment]
I'm hitting this with Terraform 0.13.6, Grafana 8.4.7 and provider 1.22.0.
After setting `password` field on the resource in Terraform, the data source gets created with an empty password.
I don't think it's a UI feature, because the data source then doesn't work and shows an authentication error.
When the password is actually set, it's shown as "configured" and there is a Reset button next to it.

**Comment by inkel** [comment]
@dryewo sorry about that! Could you share the relevant bits of your configuration, obfuscating any sensitive values? This will help us in trying to identify the issue. Thanks!
