### ISSUE TITLE
`auth` being required breaks `terraform validate`

### ISSUE THREAD

**Issue by aquarhead** [grafana/terraform-provider-grafana#117]
### Terraform Version

```
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/aws v2.70.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2
+ provider registry.terraform.io/hashicorp/tls v2.2.0
+ provider registry.terraform.io/terraform-providers/grafana v1.5.0
```

### Terraform Configuration Files
```hcl
provider "grafana" {
  version = "~> 1.5"
  url     = local.grafana_url
}
```

(I know specifying `version` here is not recommended anymore, it's not core to the problem though I believe)

### Debug Output

I don't think this is necessary, but I'm happy to provide one if requested.

### Expected Behavior

`terraform validate` does not error on the provider definition.

### Actual Behavior

```
$ terraform validate

Error: Missing required argument

  on providers.tf line 12, in provider "grafana":
  12: provider "grafana" {

The argument "auth" is required, but no definition was found.
```

### Steps to Reproduce

1. `terraform init -backend=false`
2. `terraform validate`

We use the `GRAFANA_AUTH` env var when deploying our stack, but it doesn't work with `terraform validate`.

This might have been an error in terraform core itself, but for example [the almost identical config in pagerduty provider](https://github.com/PagerDuty/terraform-provider-pagerduty/blob/e8c18e260a2ac26f67bab9b59aa3bb266db0127d/pagerduty/provider.go#L23-L27) works without issue.

```
$ terraform init -backend=false
...

$ terraform validate
Success! The configuration is valid.

$ rg "pagerduty" -A 3
providers.tf
16:provider "pagerduty" {
17-  version = "~> 1.7"
18-}
```

Or, this might be related to upgrading the provider SDK?

**Comment by ruoshan** [comment]
I get around this by exporting a dummy env for the command to run:

```
GRAFANA_AUTH=1 terraform validate
```

**Comment by julienduchesne** [comment]
You may have a pagerduty token set as an env variable because I get the same issue here: 
```
julienduchesne@Juliens-MacBook-Pro test-terraform % terraform validate           

Error: Missing required argument

  on main.tf line 35, in provider "pagerduty":
  35: provider "pagerduty" {

The argument "token" is required, but no definition was found.
```

It is probably possible to make this workflow possible by shifting the validation into the provider `configure()` function but that would also break the auto-generated documentation (show `auth` as optional). We'll have to think about this

**Comment by inkel** [comment]
I don't think there's anything to do here. As @julienduchesne mentioned with the PagerDuty provider the same error happens. This is because that provider also [defines `token` as required](https://github.com/PagerDuty/terraform-provider-pagerduty/blob/13bacf4ccbb2c3b96971a22638092c5bafff72a8/pagerduty/provider.go#L23-L27).

As stated in the [`validate` documentation](https://www.terraform.io/cli/commands/validate):

> Validate runs checks that verify whether a configuration is syntactically valid and internally consistent, regardless of any provided variables or existing state.

Given that `auth` is a required attribute the configuration isn't syntactically valid.

**Comment by julienduchesne** [comment]
We cannot implement this without breaking our provider attribute validations. I suggest exporting dummy env variables as mentioned in the thread

> 
> ```
> GRAFANA_AUTH=1 terraform validate
> ```
