### ISSUE TITLE
Feature Request - Add Ability to Set dashboard_uid for Reference in grafana_rule_group

### ISSUE THREAD

**Issue by Saske912** [grafana/terraform-provider-grafana#1215]
Dear Grafana Development Team,

I hope this message finds you well. I am currently using the grafana_rule_group resource in Terraform to configure alert rules in Grafana. While working with this resource, I've encountered a scenario where it would be highly beneficial to have the ability to explicitly set the dashboard_uid within the grafana_rule_group resource.

Currently, the grafana_rule_group resource does not provide an attribute to specify the UID of the associated dashboard. I believe introducing a dashboard_uid attribute would offer valuable flexibility and control for users who wish to explicitly link alert rules to specific dashboards.

Here is a suggested example of how this feature could be implemented in the Terraform configuration:

```
hcl

resource "grafana_rule_group" "example" {
  name             = "Example Rule Group"
  folder_uid       = grafana_folder.example.uid
  org_id           = 1
  interval_seconds = 60

  rule {
    name        = "Example Rule"
    condition   = "C"
    for         = "0s"
    dashboard_uid = "your_dashboard_uid_here"  # New attribute for specifying the dashboard UID

    data {
      ref_id = "A"
      # ... other configurations ...
    }
  }
}

```
This enhancement would empower users to explicitly associate alert rules with dashboards, providing more granular control over the relationships between rules and dashboards.

I appreciate your consideration of this feature request and look forward to seeing continued improvements in Grafana.

Best regards,
Mikhail Prigorodov
saveloy@yandex.ru

**Comment by julienduchesne** [comment]
Could you use a label for this?

```
resource "grafana_rule_group" "my_alert_rule" {
  name             = "My Rule Group"
  ...
  rule {
    ...
    labels = {
      "dashboard_url" = "..."
    }
  }
}
```

**Comment by jonnydh** [comment]
Hey @julienduchesne 👋 

We'd also be interested in such a feature. Our use case:

- Folders have a max UID length of 40 chars, and simply snipping the name at 40 chars doesn't work for us, due to overlapping namespaces. So we instead do a hash of the name to generate a folder UID.
- E.g. for `this-is-an-alert-that-has-over-40-characters- blahblahblahblahblah`, we set the folderID to a hash, and keep the dashboard name as is. 

- However we cannot override what appears to be the default setting in the Grafana Alerting UI, which just slices the first 40 chars and assumes that to be the UID. So it would assume it is `this-is-an-alert-that-has-over-40-charac` rather than the hash we generate in our terraform code.
- This means there is not currently any way to fix the broken links for these 2 fields, which are displayed to our end users...
![image](https://github.com/grafana/terraform-provider-grafana/assets/60072280/ef327329-3297-4053-8f72-753302acb066)

Alternatively, if I've missed something obvious, please let me know :)
