### ISSUE TITLE
Inconsistent 404 handling

### ISSUE THREAD

**Issue by medains** [grafana/terraform-provider-grafana#172]
### Affected Resource(s)
Please list the resources as a list, for example:
- grafana_alert_notification
- grafana_data_source
- grafana_organization

### Expected Behavior

404 response from grafana results in "[WARN] removing datasource %s from state because it no longer exists in grafana"

### Actual Behavior

404 results in a crash of the provider

### Steps to Reproduce

Create any of the resources with terraform, delete manually, then run a plan.

### Important Factoids

The client in the API has been changed to respond with an error containing "status: 404 ...." instead of "404 Not Found" - some resources have been updated in line with this change - but not the resources listed.

If I can find the time, I'll create a PR to fix this, but raising this issue in the meantime to track it for others.

**Comment by RyanW8** [comment]
Running into this issue too. Found this PR which was supposed to fix it for the `grafana_data_source` resource. https://github.com/grafana/terraform-provider-grafana/pull/56/

**Comment by inkel** [comment]
I can confirm this happens for `grafana_organization`. For both `grafana_data_source` and `grafana_alert_notification` it works as expected. I'll add it to the backlog.

Note, however, that if you manage your resources with Terraform (or any other system for that matter), you shouldn't, ideally, do any kind of manual management of the resources, otherwise you'll likely encounter unexpected issues 😉

**Comment by annelaurefroment** [comment]
Running into the same issue with `grafana_synthetic_monitoring_check` with 1.19.0. can you please look into this resource as well ?
