### ISSUE TITLE
Increase Statefile Size 

### ISSUE THREAD

**Issue by sham-github** [grafana/terraform-provider-grafana#199]
Hi Team, 

we are using Grafana provider to create our dashboards but getting below error after creating a significant number of dashboards. 

**Error: rpc error: code = ResourceExhausted... 
Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4307026 vs. 4194304)**

we are using Azure RM as backend, and we don't see any compress feature for terraform statefile in our case of Azure which is there for AWS/Consul. 

This is a must needed feature since Grafana dashboards are supposed to be large and if we are managing by terraform then the provider also should work accordingly.

**Comment by julienduchesne** [comment]
I don't believe we can increase the statefile size. That `ResourceExhausted` error is probably an internal Terraform error from communicating between the main CLI and the plugin (provider)

However, a `store_dashboard_sha256` provider option was added in v1.20.0 that, if toggled, will only save a sha256 of the dashboard's content to state instead of the whole json. I will therefore consider this issue completed
