### ISSUE TITLE
BuiltInRole deploy not idempotent

### ISSUE THREAD

**Issue by nkleinberg** [grafana/terraform-provider-grafana#362]
**Terraform Version**
Terraform v0.14.4
Terraform Grafana Provider 1.12.0
Grafana Enterprise v8.3.5

**Affected Resource(s)**
grafana_builtin_role_assignment

**Terraform config**
```
      "grafana_builtin_role_assignment": {
         "editor": {
            "builtin_role": "Editor",
            "roles": [
               {
                  "global": false,
                  "uid": "${grafana_role.report_viewer.uid}"
               }
            ]
         }
      },
      "grafana_role": {
         "report_viewer": {
            "description": "Can view reports",
            "name": "Report Viewer",
            "permissions": [
               {
                  "action": "reports:read",
                  "scope": "reports:*"
               }
            ],
            "version": 1
         }
      }
```

**Expected Behavior**
`terraform deploy` should create the role + assignment to Editor on first deploy, and make no changes on second deploy.

**Actual Behavior**
As expected on first deploy, but on second deploy all built-in-role-assignments for Editor are destroyed, including the default assignments, in our case the assignment of datasources:explore to Editor, and only the built-in role assignment specified in our config is recreated.

**Comment by vtorosyan** [comment]
@nkleinberg thanks for reporting the issue. I can confirm the issue and the unintended behaviour. 

When default built-in role assignments are not present in the terraform definition, terraform is not finding them in it's state and assumes it needs to destroy them. This looks to me also an unfortunate design bottleneck with built-in roles and we are currently thinking of improving the building blocks to make solving these problems easier.

Meanwhile, we are looking for a short term fix. Note that one potential workaround (ugly one) is to redefine all default assignments in the terraform definition.

**Comment by vtorosyan** [comment]
Note that the same behaviour is expected to happen with the `grafana_role` resource, with the permissions. For example, when a custom role is defined with some permissions and later a new permission is added via API or UI, without importing it back to the terraform configuration, terraform will try to remove the permission which it can't find in the state/config.

I think this is actually aligns with how terraform does provisioning (ie you need to import a resource, before provisioning), so I don't think we need to change anything. 

For the built-in roles, I am going to send a patch for now, as given that we have fixed role assignments to built-in roles, it is very inconvenient for users to import all fixed roles first to the terraform configuration. As I mentioned above, I think it is worth to revisit this decisions, for the time being we can fix the behaviour of `grafana_builtin_role_assignment` so that it won't touch anything which is in server side, but not in terraform state.

**Comment by nkleinberg** [comment]
Thanks @vtorosyan , the PR looks like a reasonable fix from my perspective.
