### ISSUE TITLE
Document and support non-InfluxDB datasources

### ISSUE THREAD

**Issue by mdb** [grafana/terraform-provider-grafana#4]
Hi - Thanks for your work here. It would be great if `terraform-provider-grafana` documented and supported additional data sources. I may be mistaken, but it appears `terraform-provider-grafana` only supports the InfluxDB datasource at present.

**Comment by apparentlymart** [comment]
Hi @mdb,

In principle any data source supported by Grafana should work, as long as it uses the same standard configuration attributes. At the time when `grafana_data_source` was implemented, all of the data sources we knew about were possible with the attributes provided.

Since we expected Grafana's data source support to change over time, we decided to link to [Grafana's own docs on the data sources](http://docs.grafana.org/#data-sources-guides) rather than to document them all specifically within the Terraform docs (which would require us to keep the docs up-to-date with Grafana's over time.)

As a compromise, do you think it would be helpful for us to explicitly document the mapping between the names used in the tables in the Grafana docs (like in the example below) and the corresponding Terraform resource arguments? Hopefully that gives a better guide on how to translate Grafana's own docs to Terraform without us needing to duplicate all of that information and have it get potentially stale over time.

![grafana-data-source-docs](https://user-images.githubusercontent.com/20180/30390934-9059bf5e-986c-11e7-8639-dfec6ffc007a.png)

**Comment by mdb** [comment]
@apparentlymart Thanks for the response! That partially clarifies, though it's still my understanding that `terraform-provider-grafana` does not support all Grafana datasources. For example, according to [the docs](http://docs.grafana.org/http_api/data_source/#create-data-source) the request body to create an AWS CloudWatch datasource looks like the following, yet it appears to me the [resource_data_source.go](https://github.com/terraform-providers/terraform-provider-grafana/blob/master/grafana/resource_data_source.go#L170-L183) offers no mechanism through which to specify fields such as `jsonData` and `secureJsonData`. Am I mistaken?

```
    POST /api/datasources HTTP/1.1
    Accept: application/json
    Content-Type: application/json
    Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk  
  
  {
      "name": "test_datasource",
      "type": "cloudwatch",
      "url": "http://monitoring.us-west-1.amazonaws.com",
      "access": "proxy",
      "jsonData": {
        "authType": "keys",
        "defaultRegion": "us-west-1"
      },
      "secureJsonData": {
        "accessKey": "Ol4pIDpeKSA6XikgOl4p",
        "secretKey": "dGVzdCBrZXkgYmxlYXNlIGRvbid0IHN0ZWFs"
      }
  }
```

**Comment by apparentlymart** [comment]
Hmm... interesting! It looks like the docs that we're currently linking to for data sources are outdated/stale, and there are newer data sources that are not covered there. I think http://docs.grafana.org/features/datasources/ is a better place to link to now, since it both lists the built-in plugins and links to a page where information on data source plugins can be found.

Indeed it looks like `jsonData` and `secureJsonData` are new since we originally implemented `grafana_data_source`. However, it should be possible to support these via new `json_data` and `secure_json_data` arguments on the resource, leaving it up to the configuration author to provide valid JSON as a string, possibly created using the `jsonencode` function.

Unfortunately the Grafana API docs seem to be built around examples rather than a comprehensive reference of all of the possibilities, so I'm not sure if `jsonData` and `secureJsonData` is enough to support _all possible_ data source plugins, but it should at least make the CloudWatch data source usable.

At this moment the Terraform team at HashiCorp is not working on new features for this provider due to our attention being focused elsewhere, so we won't be able to develop this in-house in the short term. However, if someone else has the time and motivation to work on it we'd love to review a PR!

**Comment by mdb** [comment]
@apparentlymart Thanks for your detailed response! I'm hoping to find some time to open a PR; just thought I should create an issue, check in with you all, and confirm my assessment first. Thanks again!

**Comment by pearkes** [comment]
Over in #18 I added a cloudwatch example to the documentation, given most of this issue is resolved with that I think we can close this out!
