### ISSUE TITLE
Support readOnly attribute for Data Sources

### ISSUE THREAD

**Issue by abacus3** [grafana/terraform-provider-grafana#444]
The official HTTP API Documentation for Data Source Ressources states that there is a `readOnly` property available.

This attribute is not exposed by the terraform-provider-grafana resource schema for data sources.
Taking a look at the respective HTTP Client, we can easily determine that this property is also not incoporated there https://github.com/grafana/grafana-api-golang-client/blob/78f337ad029e335f9a7691abe60cd77adfafc257/datasource.go#L14-L40

Starting with Grafana 8.4 we have Swagger API specification files publicly available, which already includes the `readOnly` attribute:
https://github.com/grafana/grafana/blob/5866b3659e1b71ecd781e623bb5c27e931ab39cf/public/api-spec.json#L9363-L9366

Potentially, we could get rid of using https://github.com/grafana/grafana-api-golang-client and generate HTTP client go code directly from the Swagger API spec. during build time, in order to more accurately and effectively address API versioning and compatibility concerns.

A quick fix would probably just consider extending `grafana-api-golang-client` and respectively `terraform-provider-grafana` by only this single attribute.

**Comment by julienduchesne** [comment]
Yes, the Grafana OSS team is already looking into creating a client from the openapi definition. For now, we'll add it to the existing client

**Comment by julienduchesne** [comment]
See https://github.com/grafana/grafana-api-golang-client/pull/74#issuecomment-1081320992. If I look at the doc here: https://grafana.com/docs/grafana/latest/http_api/data_source/, I see that it is only there in responses, not requests. This attribute effectively shows provisioned dashboards that had the `editable: false` attribute. It cannot be set by the API (or Terraform), therefore I do not think it makes sense to add this attribute

Let me know if I'm misunderstanding. Otherwise, I'll close this issue
