### ISSUE TITLE
Import datasource "unsupported protocol scheme"

### ISSUE THREAD

**Issue by carlbordum** [grafana/terraform-provider-grafana#473]
My company is using a grafana.com managed Grafana Cloud stack:

<details>
<summary>Click to expand</summary>

```
provider "grafana" {
  alias = "cloud"
  cloud_api_key = <redacted>
}

resource "grafana_cloud_stack" "company" {
  provider = grafana.cloud

  name        = "company.grafana.net"
  slug        = "company"
  region_slug = "us"

  lifecycle {
    prevent_destroy = true
  }
}
```

</details>

We need to manage the Prometheus provided by the stack, but I am having trouble importing it. I extend our terraform with:
```
resource "grafana_data_source" "prometheus" {
  provider = grafana.cloud

  type = "prometheus"
  name = "grafanacloud-company-prom"
}
```

And then run:

```
$ terraform import 'grafana_data_source.prometheus' ID
grafana_data_source.prometheus: Importing from ID "ID"...
grafana_data_source.prometheus: Import prepared!
  Prepared grafana_data_source for import
grafana_data_source.prometheus: Refreshing state... [id=ID]
╷
│ Error: Get "/api/datasources/ID": unsupported protocol scheme ""
│
│
```

Maybe it's just my limited terraform understading, but the [documentation for importing](https://github.com/grafana/terraform-provider-grafana/blob/3119f17d7e3b0f82f89a3ff44581c1d30677d078/docs/resources/data_source.md#import) doesn't really make sense. It shows an invalid syntax.

### Terraform Version

* Terraform: v1.1.9
* Terraform Grafana Provider: v1.22.0
* Grafana: ...

### Affected Resource(s)

Please list the resources as a list
* grafana_data_source

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here?
- https://github.com/grafana/terraform-provider-grafana/issues/252
- https://github.com/grafana/terraform-provider-grafana/pull/396

**Comment by inkel** [comment]
@carlbordum can I ask how are you obtaining the ID?

I used my local Grafana installation and was able to import by either ID or UID.

These are my current settings:

```
$ terraform version
Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/grafana/grafana v1.22.0

$ cat datasources.tf
resource "grafana_data_source" "prometheus" {
  name = "prometheus"
  type = "prometheus"
}
```

In order to obtain the ID/UID I checked Grafana's HTTP API by visiting http://localhost:3000/api/datasources

This is when importing by UID:

```
$ terraform import grafana_data_source.prometheus 9R2F9r3Gk
grafana_data_source.prometheus: Importing from ID "9R2F9r3Gk"...
grafana_data_source.prometheus: Import prepared!
  Prepared grafana_data_source for import
grafana_data_source.prometheus: Refreshing state... [id=5]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

Then I cleared up my Terraform state and tried again with the ID:

```
$ terraform import grafana_data_source.prometheus 5
grafana_data_source.prometheus: Importing from ID "5"...
grafana_data_source.prometheus: Import prepared!
  Prepared grafana_data_source for import
grafana_data_source.prometheus: Refreshing state... [id=5]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

I agree with you that the documentation isn't 100% clear on how to import this resource. I'd like to see if I can help you with this before we rewrite the docs, what do you think?

**Comment by julienduchesne** [comment]
The issue is that you are using a Grafana cloud provider to manage instance resources
You need to create a new "provider" object to manage resources inside the stack
See https://github.com/grafana/terraform-provider-grafana/blob/master/docs/index.md#creating-a-grafana-cloud-stack-provider

Since we've added cloud and synthetic monitoring, we're definitely missing some checks in resources themselves. Ideally, the resource should have printed a helpful error message

**Comment by carlbordum** [comment]
Ah gotcha. That was the issue, thank you.

I still have a problem though. I want the Prometheus created by the `grafana_cloud_stack` to be my default datasource, but there are no options for that.

I tried terraform-importing the Promtheus and then setting `is_default = true`, but `terraform apply` tells me:

```
grafana_data_source.prometheus: Modifying... [id=9]
╷
│ Error: status: 403, body: {"message":"Cannot update read-only data source"}
```

I have created https://github.com/grafana/terraform-provider-grafana/issues/476 with the feature request.

Again, thank you.
