### ISSUE TITLE
`grafana_cloud_stack` allow setting default datasource

### ISSUE THREAD

**Issue by carlbordum** [grafana/terraform-provider-grafana#476]
It would be very handy to be able to declare which datasource is the default. This is helpful for Organisations migrating to the terraform provider, as they may have tons of dashboards relying on the default datasource.

Alternatively, make the prometheus default as it is when you start a new stack.

**Comment by julienduchesne** [comment]
Blocked, unsupported in the Cloud API

**Comment by julienduchesne** [comment]
I verified this with the current version:
- In the UI, like in Terraform, the default DS when you create a stack is the prometheus (mimir) instance
- In the UI, like in Terraform, you cannot set the default status for a provisioned datasource
- You can create a new datasource and set that one as default, so I'd say to just ignore the provisioned prometheus datasource and create a new one

I am closing this because this is not a blocker and the API itself doesn't seem to support modifying provisioned datasource
