### ISSUE TITLE
Grafana Data Source Timeout

### ISSUE THREAD

**Issue by AlHood77** [grafana/terraform-provider-grafana#578]
The 'Timeout' field of the HTTP pane doesn't appear to be mapped in the grafana_data_source. Is that something which could be added?

<img width="578" alt="Screenshot 2022-08-04 at 13 41 10" src="https://user-images.githubusercontent.com/45075866/182849471-1f16acab-c90a-4aa1-b385-559ae0d618f8.png">

**Comment by abacus3** [comment]
I do believe that we can extend: https://github.com/grafana/terraform-provider-grafana/blob/f4a15e028dd03b8aee4c3831020805a97ce6c083/grafana/resource_data_source.go#L113 with a new parameter called `timeout` and respectively consider this new parameter during the JSON model creation in: https://github.com/grafana/terraform-provider-grafana/blob/f4a15e028dd03b8aee4c3831020805a97ce6c083/grafana/resource_data_source.go#L695 once it is implemented in https://github.com/grafana/grafana-api-golang-client/blob/1cb3f2ec1c3fcd0fef5cb6aae377eb8c99fb69dc/datasource.go#L87

@julienduchesne since we have https://raw.githubusercontent.com/grafana/grafana/main/public/api-spec.json with https://github.com/grafana/grafana/pull/40528, it might be a reasonable approach to replace grafana-api-golang-client with a client generated based on the OpenAPI spec, as already mentioned in https://github.com/grafana/terraform-provider-grafana/issues/197#issuecomment-1047012476
