### ISSUE TITLE
grafana_notification_policy only creates single resource

### ISSUE THREAD

**Issue by NickAdolf** [grafana/terraform-provider-grafana#624]
### Terraform Version
* Terraform: 1.22
* Terraform Grafana Provider: 1.27.0
* Grafana: 9.1 - cloud

### Affected Resource(s)
grafana_notification_policy

I'm creating grafana_notification_policy resources within a module, that is implemented leveraging a for_each. I'm trying to create > 50 notification policies & no matter changes I make it seems only one of the resources is actually created and\or shows in Grafana. The plan seems to think the single existing resource matches with all other instances, resulting in a plan trying to update the existing resource to each of the desired values, only one wins out when applied.

### Expected Behavior
Every resource declared should result in a new notification policy in Grafana.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.  Create multiple of the resource.

**Comment by NickAdolf** [comment]
I'm wondering if it is only trying to create the root policy? I don't see this mentioned in the docs. This is a pretty big show stopper for us.

_This root notification policy cannot be edited through the UI_

**Comment by RealOrangeOne** [comment]
It looks like this is actually a limitation with grafana itself. Only a [single API endpoint](https://grafana.com/docs/grafana/next/developers/http_api/alerting_provisioning/#notification-policies) is provided to manage the entire notification policy tree, therefore only a single `resource` can exist to control it. The fix is actually to allow controlling the individual policies. The terraform integration could probably shim over the single endpoint, but that's probably not ideal.

**Comment by NickAdolf** [comment]
I had just realized that myself, seems a very odd implementation, but I will close this out.

**Comment by NickAdolf** [comment]
For those poking around, you get one resource, so in my case I have 50+ policies nested inside.

**Comment by alexweav** [comment]
Yes, you currently have to provision the entire tree as you observed, this is more a property of the API rather than Terraform.

This was an intentional design decision - essentially, notification policy nodes can interfere with each other in the prometheus model. You might provision 50 policy entries, but a stray hand-created entry on the server could route a notification prematurely and cause part of the tree to behave in an unexpected way.

We wanted to make the behavior completely deterministic, so if you provision the same routing on two different Grafanas they should act exactly the same. We don't want users to accidentally lose notifications! However, the drawback here is that to guarantee this, we must make sure that the entire policy tree in Grafana is also present in Terraform - hence the single resource.
