### ISSUE TITLE
silence resource

### ISSUE THREAD

**Issue by RomKimchi** [grafana/terraform-provider-grafana#660]
hi! i need silences to manage my grafana.
can you add a resource for that?

example of a similar feature in grafana api: /api/alertmanager/{DatasourceUID}/api/v2/silences

thanks!

**Comment by alexweav** [comment]
Hi, unfortunately silences at their core aren't very compatible with how Terraform works. Silences are forcibly expired after a certain amount of time, that's by default pretty short. It's intended to be more of an ad-hoc mute of an alert that is pinging you right now, not something that's managed long term.

The resource would be constantly deleted out from underneath terraform because of silence expiry, and there is no guarantee that Terraform runs often enough to refresh it.

Have you tried mute timings? A mute timing is like a silence, but indefinite. It's meant for this exact same use case.
https://grafana.com/docs/grafana/latest/alerting/notifications/mute-timings/
https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/mute_timing 

A silence is saying "mute this alert that's firing _right now_" where a mute timing is saying "silence this alert if it fires in the future"

**Comment by RomKimchi** [comment]
hi again! thanks for answering so fast.
your explanation really makes sense, thanks! My the problem with mute timing is that they are attached to the "whole" notification policy and not to a label. do you know how can i silence an alert based on a label using terraform or which feature i should ask you to add to be able to do it?

**Comment by alexweav** [comment]
Sure! You can add a dedicated sub-policy for that label underneath the top-level policy. Sub-policies let you route things really granularly.

Given a mute timing called `my_mute_timing`, and say you want to apply it to label `mylabel=myvalue`, use something like:

```
resource "grafana_notification_policy" "my_policy" {
    ... normal top-level policy fields ...
    group_by = ...
    contact_point = ...

    policy {
        matcher {
            label = "mylabel"
            match = "="
            value = "myvalue"
        }
        group_by = ["..."]
        contact_point = <same as top level policy>
       mute_timings = [grafana_mute_timing.my_mute_timing.name]
    }
}
```
This tree says to apply `my_mute_timing` where mylabel=myvalue, otherwise use the top-level policy for all other notifications.

You can also use regexes, you can do something like `match = "=~"` and `value = "some-regex.*"` in the matcher to have it match patterns in the label values.

Here are some extra docs on what all you can do:
https://grafana.com/docs/grafana/latest/alerting/notifications/

**Comment by alexweav** [comment]
It seems like this is answered, and we don't have immediate plans of adding a silence resource because of the reasons listed above, so I'll go ahead and close this. Feel free to re-open if this hasn't covered what you are looking for.

**Comment by cpinflux** [comment]
I get the point of the comments regarding the automatic expiration, however what if it's meant to automatically expire in 25 years?

Route 1 is naturally to clean up the data in the first place, write "better" alert rules etc., but that's not always possible. Especially not in such a operator user friendly way as silences allow when, for example, a certain customer's environment should be excluded from alerts being raised.
