### ISSUE TITLE
Allow alerting resources to be optionally editable from UI

### ISSUE THREAD

**Issue by teokeecheng** [grafana/terraform-provider-grafana#697]
Currently, for any rule group created from terraform, it will show a status 'Provisioned', and not allow any amendment through console. However, when we view it from console, not all alert details are displayed (e.g. queries and criteria). Would be good if there is an option in terraform resource to indicate if the alert can be editable from UI for testing and flexibility.

**Comment by greatvovan** [comment]
I do not think this issue is relevant to TF provider project. This is how provisioned alerts work in Grafana. If you provision an alert through [provisioning API](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/), you'll see the same.

There are also open issues for this feature request in Grafana repo. See: https://github.com/grafana/grafana/issues/57793

**Comment by HartmannVolker** [comment]
Related issue in the grafana repo: https://github.com/grafana/grafana/issues/51211

**Comment by tomashejatko** [comment]
Hello, this is now resolved upstream in Grafana 9.3.0 and should be implemented: https://github.com/grafana/grafana/pull/58410

**Comment by greatvovan** [comment]
Hello
Reading the comments to the pull request, I understand the option was added to API only. The motivation was to relief the pain for all kinds of provisioned alerts. I am wondering, how it will help me with Terraformed alerts?

**Comment by tomashejatko** [comment]
I see you have posted a question to the original issue but with a somewhat negative answer. So maybe dumb question from my side: 

I thought that TF provider is using Grafana API to create dashboard alerts and stuff (My Grafana access logs and https://github.com/grafana/terraform-provider-grafana/blob/master/grafana/resource_alerting_rule_group.go#L11 kinda approves this), so I thought that you can add an optional parameter to https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/rule_group which will send `x-disable-provenance` header when set to true.

But maybe the problem is that workaround from https://github.com/grafana/grafana/pull/58410 is using provisioning API and TF provider is using "another API"?

Just to clarify what I want from this feature (using similar procedure from the dashboard and for alert rules creation):

1. I have `grafana_rule_group` resource defined with a full "data model" in my .tf file
2. I want to go to UI to make changes to the alert, even changing the threshold is much more feasible if you see graphical representation
3. Save alert group in UI
4. Make `terraform plan` which tells me what I have to change in .tf files

Maybe it sound bit complicated but I am doing this with my terraformed dashboards for about 3 years :)

**Comment by greatvovan** [comment]
Your flow makes sense, I believe many of us rely on UI support prior terraforming rules. To be honest, I do not see the feature implemented in https://github.com/grafana/grafana/pull/58410 much helpful.

**Comment by tomashejatko** [comment]
Issue says: "This will create alert rules as if they were created via UI and make the editable."

This will make point 2 from my list possible, now I can only view that alert, with this feature it will be editable

**Comment by greatvovan** [comment]
That's for API-created. How do you enforce that for terraformed rules?

**Comment by jantman** [comment]
I've dug into this quite a bit, and believe I've identified what's going on.

* Yes, the Grafana provider uses the alert provisioning API; there's no separate API for terraform. If there's any question about this, just look at the actual HTTP requests from the provider.
* You _can_ pass the `X-Disable-Provenance` header through to the API, via the `http_headers` parameter on the provider.
* *However* the work done in https://github.com/grafana/grafana/pull/58410 only looks at this header for the `POST /api/v1/provisioning/alert-rules` and `PUT /api/v1/provisioning/alert-rules/{UID}` API endpoints. If you are specifying a `folder_uid` for your rule group, then the terraform provider is using the `/api/v1/provisioning/folder/{FolderUID}/rule-groups/{UID}` endpoint. And _that_ endpoint does not look at the provenance header.

https://github.com/grafana/grafana/issues/63047 is currently open for this exact issue, and a PR to fix it ( https://github.com/grafana/grafana/pull/63650 ) was opened yesterday and is currently a draft. This should be fixed once that PR is finished, merged, and released.

**Comment by abualy** [comment]
i believe this is now released in grafana 10.0.0, is the plan now to go forward ? :D

**Comment by diegombeltran** [comment]
I just updated to 10.0.2, but even with the header I'm not able to update the alerts by API:
`cannot change provenance from 'api' to ""`

**Comment by awhiriskey** [comment]
I am also on 10.0.2 and getting the same `cannot change provenance from 'api' to ""` when trying to update an alert via the API

**Comment by sdepablos** [comment]
I'm in version 10.2.0-59542pre with  
```
Terraform v1.5.5
on linux_amd64
+ provider registry.terraform.io/grafana/grafana v2.2.0
```
and adding/removing the 
```
  http_headers = {
    "X-Disable-Provenance" = "disabled"
  }
```
inside the provider changes my alerts from `provisioned` to nothing. 

**UPDATE**

It works for 
- `grafana_message_template`
- `grafana_rule_group`
- `grafana_notification_policy`

but not for 
- `grafana_contact_point`

with the error 
```
│ Error: status: 500, body: {"message":"cannot change provenance from 'api' to ''"
```

Looks like the `X-Disable-Provenance` header is still not working properly for all API endpoints.

**UPDATE 2**

As per their documentation for Grafana 10 https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/#provision-grafana-alerting-resources 

> Currently, provisioning for Grafana Alerting supports alert rules, contact points, mute timings, and templates. Provisioned alerting resources using file provisioning or Terraform can only be edited in the source that created them and not from within Grafana or any other source. For example, if you provision your alerting resources using files from disk, you cannot edit the data in Terraform or from within Grafana.

>To allow editing of provisioned resources in the Grafana UI, add the X-Disable-Provenance header to the following requests in the API:

>POST /api/v1/provisioning/alert-rules
PUT /api/v1/provisioning/folder/{FolderUID}/rule-groups/{Group} (calling this endpoint will change provenance for all alert rules within the alert group)
POST /api/v1/provisioning/contact-points
POST /api/v1/provisioning/mute-timings
PUT /api/v1/provisioning/policies
PUT /api/v1/provisioning/templates/{name}

but only works creating  `contact points` (POST), not updating them (PUT).

**Comment by julienduchesne** [comment]
Planning to add better TF support for this soon
