### ISSUE TITLE
`default_region` param for cloudwatch datasource does not work

### ISSUE THREAD

**Issue by aliabbasjaffri** [grafana/terraform-provider-grafana#714]
### Terraform Version
* Terraform: 1.3.0
* Terraform Grafana Provider: 1.30.0
* Grafana: v9.2.3-997144b7

### Affected Resource(s)
Please list the resources as a list, for example:
* `grafana_data_source`
If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# terragrunt.hcl
grafana_data_sources = {
  "cloudwatch" = {
    type = "cloudwatch"
    name = "cloudwatch_datasource"
    json_data_encoded = {
      default_region = "us-west-2"
      auth_type = REDACTED
    }
  }
}


# main.tf
resource "grafana_data_source" "data_source" {
  provider = grafana.grafana_management_dev

  for_each = var.grafana_data_sources

  type = each.value.type
  name = each.value.name
  url = each.value.url
  json_data_encoded = jsonencode(each.value.json_data_encoded)
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
default_region in Grafana cloudwatch datasource should have been selected

### Actual Behavior
default region is not selected by default
<img width="792" alt="Screenshot 2022-11-09 at 17 45 59" src="https://user-images.githubusercontent.com/4748985/200890267-5a36eebb-357e-40b5-921d-e855ff93750b.png">

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by julienduchesne** [comment]
When saving a cloudwatch datasource, it looks like the payload should be `defaultRegion`. Not `default_region`: 
![image](https://user-images.githubusercontent.com/29210090/201226777-98990929-31e6-43d2-a181-bdbc94ca07c4.png)

I'm sorry if this was confusing. The `json_data_encoded` takes in the raw json data, while the old deprecated `json_data` has attributes defined manually. We switched over because it wasn't sustainable to add every attribute manually. We also can't convert automatically from camelCase to snake_case because not all plugins use the same casing

**Comment by aliabbasjaffri** [comment]
Just verified, this works! Thank you @julienduchesne
