### ISSUE TITLE
Support Setting of org_id outside of provider block

### ISSUE THREAD

**Issue by eviscares** [grafana/terraform-provider-grafana#747]
Hey,

with the current state of terraform I think that the abstraction of tying org_id to the provider is proving a lot more troublesome, as you would for example need to create a grafana org in one module, pass out its org_id to a provider, and then pass that provider into a new module that can then for example create data sources and dashboards for an organization.
At least Datasources and Users should support this out of the box as you could just set the org_id on the request to create them.

I think this would really simplify working with the provider.

**Comment by julienduchesne** [comment]
This is going to happen. I'm planning to introduce an `org_id` attribute to resources gradually. Stay tuned!

**Comment by julienduchesne** [comment]
Remaining resources to support:
- Datasource
- Team
- Folder
- Datasources (`data_xxx`)

Planning to remove the global `org_id` afterwards because it complicates things and is confusing. Some resources support `org_id` but not all (example: user is org-agnostic and alerting doesn't use the same header, so the global setting doesn't work)

**Comment by adkinsjd** [comment]
We are really excited about the addition of org_id to these resources - it would make our configuration much, much cleaner!

Is there a target timeline the completion of this project?

**Comment by pschulten** [comment]
Is there something, you need help with?
