### ISSUE TITLE
[Feature Request] Support dashboard overwriting

### ISSUE THREAD

**Issue by Xopherus** [grafana/terraform-provider-grafana#8]
It doesn't look like overwriting dashboards is supported via this library, but it is a supported by the [Grafana Dashboard API](http://docs.grafana.org/http_api/dashboard/#create-update-dashboard). 

Admittedly I'm a bit torn on this issue, because it seems like by default Grafana wants you to ensure that when you make updates it expects a JSON file with a version number higher than what is currently loaded. This seems like a good practice. On the other hand, my team frequently makes live tweaks to dashboards but we'd like to use terraform as the source of truth. This also helps us deploy dashboards to multiple environments in an automated fashion. In that case we could just export the dashboard and then have terraform recreate it. In that workflow we'd actually have to bump the version number because the version numbers would be identical. 

What do you all think? Should this be supported?

**Comment by apparentlymart** [comment]
Hi @Xopherus! Thanks for this suggestion.

The expected model for a Terraform resource is that it should fail if asked to create something that already exists outside of Terraform, to prevent accidentally bringing some object under Terraform's management, but should be able to update in-place an object that Terraform created, even if it has been edited by some other means outside of Terraform.

The `grafana_dashboard` resource currently does not support "update" as an action, instead expecting to delete and re-create the dashboard each time it has changed. We could be truer to Terraform's intended workflow here by capturing the version number on refresh and then handling the version number increment on apply, thus allowing Terraform to update a dashboard in-place if it's changed.

I don't think it's a good idea to overwrite a dashboard that wasn't originally _created_ by Terraform, since that violates usual expectations for Terraform's behavior and may lead to data loss when users make mistakes.

----

From your description of the problem it sounds like part of what you're trying to solve is the development workflow for Grafana dashboards since it's pretty unreasonable to author a Grafana dashboard directly in JSON, and so you generally want to build it _in Grafana_ and export it.

I originally developed this provider in a previous role where we addressed this problem by having dashboard developers run Grafana locally on their dev machines, just like a dev environment for any other app, and work on the dashboard interactively there. They would then export the JSON into the Terraform config and shut down the local instance. The Grafana instances running in our "real" environments were then configured such that they could be edited _only_ by Terraform.

Although this approach does indeed have some extra overhead vs. designing a dashboard "in production", it allowed us to ensure consistency between the staging and production environments, since _neither_ environment would already have the dashboard and thus risk us inadvertently looking at the manually-created version instead of the Terraform-created version.

**Comment by pearkes** [comment]
With the new APIs this seems _more_ possible to represent a workflow that normal Terraform users would expect. http://docs.grafana.org/http_api/dashboard/#create-update-dashboard.

The `uid` parameter seems to allow you to both create and destroy (if your workflow fits that) each time there is an update made or to just overwrite and existing dashboard. I believe given this new API it is much more Terraform friendly and thus could handle this well.

**Comment by a3linux** [comment]
Anyone can handle this as the Grafana API seems support the override parameter and the go-grafana-api also have this when do SaveDashboard. Not good at golang, only did static check.

**Comment by svenschwermer** [comment]
I believe this would solve our problem of not having stable links to the dashboard created by Terraform after a delete/re-create cycle. Or is there another way to achieve this?

**Comment by shalyng** [comment]
@Xopherus, @mlclmj, can this issue now be closed?

**Comment by Xopherus** [comment]
I think so! Thanks @shalyng

**Comment by trotttrotttrott** [comment]
Overwrite property added in https://github.com/grafana/terraform-provider-grafana/pull/214
