### ISSUE TITLE
Mimir alerts support ?

### ISSUE THREAD

**Issue by hajdukda** [grafana/terraform-provider-grafana#871]
Hello,

This is more of a question than feature request - but I would like to know how to create MIMIR alerts using this provider.
Have not found any example on how to define that.

Every example is using default Grafana integration.

**Comment by julienduchesne** [comment]
It's not possible currently. The best tool we have to write to Mimir is `mimirtool`: https://grafana.com/docs/mimir/latest/operators-guide/tools/mimirtool/

**Comment by abacus3** [comment]
The new OpenAPI Spec documents the respective endpoints for managing data source managed alerts: https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/public/api-merged.json

At least rules management in general seem to be supported by the new OpenAPI generated go-client: https://pkg.go.dev/github.com/grafana/grafana-openapi-client-go@v0.0.0-20240126032018-bd23c00af697/client/recording_rules

So it seems the terraform `resource` and `data` implementations could be created already for recording and altering rules.

I am also not sure about the alertmanager integrations, as they are being called by the Grafana UI, but not documented in the OpenAPI spec. https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/contact_point seems to only configure the Grafana AM.

**Comment by julienduchesne** [comment]
I will close this issue because:
- For the `Grafana` alertmanager, you can use the existing alerting resources. 
- If we're talking about expanding those resources to use a different alertmanager within Grafana, then this issue is a duplicate of https://github.com/grafana/terraform-provider-grafana/issues/799
- For OSS mimir, it'd probably be an other provider. I've seen this provider being use with success: https://registry.terraform.io/providers/fgouteroux/mimir/0.2.4. Note that you can also use this provider for Grafana Cloud metrics
