### ISSUE TITLE
[Feature request] Have Grafana dashboards be stored by uid instead of slug

### ISSUE THREAD

**Issue by teddylear** [grafana/terraform-provider-grafana#95]
Hi there,

Currently Grafana dashboards are stored by their slug instead of uid using one of the newer versions of Grafana. This causes failures with having multiple dashboards being named the same under different folders in the same Grafana instance. With changing to uid for dashboards, this should resolve the issue. 

### Affected Resource(s)
- resource_dashboard

**Comment by tonglil** [comment]
There is some work on this in this PR: https://github.com/terraform-providers/terraform-provider-grafana/pull/84

The upstream library supports using uid now, if someone wants to give this a try.

**Comment by pabloajz** [comment]
any update on this? 
Grafana 8 has removed from the API the slug id > https://github.com/grafana/grafana/pull/35104
So when upgrading to Grafana v8 this provider basically stops working. 

For existing resources > On first apply it shows a version mismatch and try to recreate the dashboard, then it fails because the dashboard already exists with the same name. 

For new resources it creates the dashboard but it fails to store the resource into the terraform state, I guess because the API is not accepting/returning the slug anymore

As solution we had to rollback Grafana to v7 and remove manually affected dashboards , recreating them again with terraform

This is blocking upgrading Grafana to v8

EDIT: IMO this should be categorized as a BUG and not as Feature  request

**Comment by trotttrotttrott** [comment]
Resolved in https://github.com/grafana/terraform-provider-grafana/pull/217
